osx_image: xcode11.5
language: swift
cache:
  cocoapods: true

env:
 ZCASH_NETWORK_ENVIRONMENT : TESTNET
before_install:
- brew update
xcode_project: Zircles.xcworkspace # path to your xcodeproj folder
xcode_scheme: Zircles
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone 8
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install
script:
- set -o pipefail && xcodebuild test -workspace Zircles.xcworkspace -scheme Zircles -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.5' ONLY_ACTIVE_ARCH=YES | travis_wait 10 xcpretty
