osx_image: xcode11.5
language: swift

env:
 ZCASH_NETWORK_ENVIRONMENT : TESTNET
before_install:
- brew update
podfile: Example/Podfile
before_install:
 - brew install curl
 - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
 - cargo install -f cargo-lipo
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install
script:
- set -o pipefail && xcodebuild test -workspace Zircles.xcworkspace -scheme Zircles -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.5' ONLY_ACTIVE_ARCH=YES | xcpretty
